version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
      MYSQL_DATABASE: app
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT_OUT}:${DB_PORT_IN}"
    volumes:
      - ./data/db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: ${DB_PORT_IN}
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "${PHP_PORT_OUT}:${PHP_PORT_IN}"

  twitch:
    image: node:twitch_bot
    build:
      context: twitch
      dockerfile: Dockerfile
    container_name: twitch
    command: nodemon bot.js
    volumes:
      - ./twitch:/usr/src/twitch
      - ./twitch/node_modules:/usr/src/twitch/node_modules
    ports:
      - "${TWITCH_PORT_OUT}:${TWITCH_PORT_IN}"
    depends_on:
      - db_socket

  discord:
    image: node:discord_bot
    build:
      context: discord
      dockerfile: Dockerfile
    container_name: discord
    command: nodemon bot.js
    volumes:
      - ./discord:/usr/src/discord
      - ./discord/node_modules:/usr/src/discord/node_modules
    ports:
      - "${DISCORD_PORT_OUT}:${DISCORD_PORT_IN}"
    depends_on:
      - db_socket

  db_socket:
    image: node:db_socket
    build:
      context: db_socket
      dockerfile: Dockerfile
    container_name: db_socket
    command: nodemon server.js
    volumes:
      - ./db_socket:/usr/src/db_socket
      - ./db_socket/node_modules:/usr/src/db_socket/node_modules
    ports:
      - '${NODE_DB_PORT_OUT}:${NODE_DB_PORT_IN}'
    depends_on:
      - db

