version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
      MYSQL_DATABASE: app
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT_OUT}:${DB_PORT_IN}"
    volumes:
      - ./data/db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: ${DB_PORT_IN}
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "${PHP_PORT_OUT}:${PHP_PORT_IN}"

  twitch:
    image: node:twitch_bot
    build:
      context: twitch
      dockerfile: Dockerfile
    container_name: twitch
    command: nodemon bot.js
    volumes:
      - ./twitch:/usr/src/twitch
      - ./twitch/node_modules:/usr/src/twitch/node_modules
    ports:
      - '${TWITCH_PORT_OUT}:${TWITCH_PORT_IN}'
    # depends_on:
    #   - db_socket
